
import React, { useState } from 'react';
import { usePortfolio } from '../context/PortfolioContext';
import { useAuth } from '../context/AuthContext';
import PortfolioView from '../components/PortfolioView';
import { 
  Rocket, Github, CheckCircle, Loader2, Link as LinkIcon, Download, Cloud, X 
} from 'lucide-react';
import { TEMPLATES } from '../constants';
import JSZip from 'jszip';

interface GithubSyncModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSync: (data: { name: string; description: string; visibility: 'public' | 'private' }) => void;
  isSyncing: boolean;
  isGithubConnected: boolean;
  isAuthLoading: boolean;
  onConnectGithub: () => void;
}

const GithubSyncModal: React.FC<GithubSyncModalProps> = ({ 
  isOpen, 
  onClose, 
  onSync, 
  isSyncing,
  isGithubConnected,
  isAuthLoading,
  onConnectGithub
}) => {
  const [repoName, setRepoName] = useState('');
  const [description, setDescription] = useState('');
  const [visibility, setVisibility] = useState<'public' | 'private'>('private');

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[100] flex justify-end">
       {/* Backdrop */}
       <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={onClose} />
       
       {/* Drawer */}
       <div className="relative w-full max-w-md bg-[#111] border-l border-white/10 h-full p-8 shadow-2xl animate-in slide-in-from-right duration-300 flex flex-col">
          <div className="flex items-center justify-between mb-8">
            <h2 className="text-xl font-bold font-display text-white">Sync to GitHub</h2>
            <button onClick={onClose} className="text-slate-400 hover:text-white transition-colors">
              <X className="w-5 h-5" />
            </button>
          </div>

          {!isGithubConnected ? (
             <div className="flex-1 flex flex-col items-center justify-center text-center space-y-6 animate-in fade-in zoom-in duration-500">
                <div className="w-24 h-24 bg-slate-900 rounded-3xl flex items-center justify-center border border-slate-800 shadow-2xl mb-4 relative overflow-hidden group">
                  <div className="absolute inset-0 bg-[#ccff00]/10 opacity-0 group-hover:opacity-100 transition-opacity" />
                  <Github className="w-10 h-10 text-white" />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-white mb-2">Authorization Required</h3>
                  <p className="text-slate-400 text-sm leading-relaxed max-w-xs mx-auto">
                    To create repositories and push code, you must authorize Portfoli AI to access your GitHub account.
                  </p>
                </div>
                <button 
                  onClick={onConnectGithub}
                  disabled={isAuthLoading}
                  className="w-full py-4 bg-[#24292e] hover:bg-[#2f363d] text-white rounded-xl font-bold uppercase tracking-widest transition-all flex items-center justify-center gap-3 border border-white/10 hover:border-white/30 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  {isAuthLoading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Github className="w-4 h-4" />}
                  {isAuthLoading ? 'Connecting...' : 'Connect GitHub'}
                </button>
             </div>
          ) : (
            <>
              <div className="space-y-6 flex-1 overflow-y-auto animate-in fade-in slide-in-from-right-4 duration-500">
                 <div className="space-y-2">
                   <label className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">New repository name</label>
                   <input 
                     type="text" 
                     value={repoName}
                     onChange={e => setRepoName(e.target.value)}
                     className="w-full bg-[#0a0a0a] border border-white/10 rounded-xl p-4 text-white text-sm focus:border-[#ccff00] focus:outline-none transition-colors font-mono"
                     placeholder="my-portfolio-v1"
                   />
                 </div>

                 <div className="space-y-2">
                   <label className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Description</label>
                   <textarea 
                     value={description}
                     onChange={e => setDescription(e.target.value)}
                     className="w-full bg-[#0a0a0a] border border-white/10 rounded-xl p-4 text-white text-sm focus:border-[#ccff00] focus:outline-none transition-colors resize-none h-32 font-mono"
                     placeholder="A professional portfolio generated by Portfoli AI..."
                   />
                 </div>

                 <div className="space-y-3 pt-2">
                   <label className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Visibility</label>
                   
                   <label className={`flex items-start gap-4 p-4 rounded-xl border cursor-pointer transition-all ${visibility === 'private' ? 'bg-[#ccff00]/5 border-[#ccff00] text-white' : 'bg-[#0a0a0a] border-white/10 text-slate-400 hover:border-white/30'}`}>
                     <div className="mt-1">
                       <div className={`w-4 h-4 rounded-full border flex items-center justify-center transition-colors ${visibility === 'private' ? 'border-[#ccff00]' : 'border-slate-600'}`}>
                         {visibility === 'private' && <div className="w-2 h-2 rounded-full bg-[#ccff00]" />}
                       </div>
                     </div>
                     <div>
                       <div className="font-bold text-sm mb-0.5">Private</div>
                       <div className="text-[10px] opacity-70 font-mono">Only you can access this repo on GitHub.com</div>
                     </div>
                     <input type="radio" className="hidden" name="visibility" checked={visibility === 'private'} onChange={() => setVisibility('private')} />
                   </label>

                   <label className={`flex items-start gap-4 p-4 rounded-xl border cursor-pointer transition-all ${visibility === 'public' ? 'bg-[#ccff00]/5 border-[#ccff00] text-white' : 'bg-[#0a0a0a] border-white/10 text-slate-400 hover:border-white/30'}`}>
                     <div className="mt-1">
                       <div className={`w-4 h-4 rounded-full border flex items-center justify-center transition-colors ${visibility === 'public' ? 'border-[#ccff00]' : 'border-slate-600'}`}>
                         {visibility === 'public' && <div className="w-2 h-2 rounded-full bg-[#ccff00]" />}
                       </div>
                     </div>
                     <div>
                       <div className="font-bold text-sm mb-0.5">Public</div>
                       <div className="text-[10px] opacity-70 font-mono">This repo will be discoverable by everyone.</div>
                     </div>
                     <input type="radio" className="hidden" name="visibility" checked={visibility === 'public'} onChange={() => setVisibility('public')} />
                   </label>
                 </div>
              </div>

              <div className="mt-8 pt-6 border-t border-white/10">
                <button 
                  onClick={() => onSync({ name: repoName, description, visibility })}
                  disabled={isSyncing || !repoName}
                  className="w-full py-4 bg-[#ccff00] hover:bg-white text-black rounded-xl font-bold uppercase tracking-widest transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-3"
                >
                  {isSyncing ? <Loader2 className="w-4 h-4 animate-spin" /> : <Github className="w-4 h-4" />}
                  Create GitHub repository
                </button>
              </div>
            </>
          )}
       </div>
    </div>
  );
};

const ActionHeader: React.FC = () => {
  const { portfolioData } = usePortfolio();
  const { user, loginWithGitHub, isLoading: isAuthLoading } = useAuth();
  const [syncing, setSyncing] = useState(false);
  const [deploying, setDeploying] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);
  const [showToast, setShowToast] = useState<'sync' | 'deploy' | 'download' | null>(null);
  const [liveUrl, setLiveUrl] = useState('');
  const [isGithubModalOpen, setIsGithubModalOpen] = useState(false);

  // Simple check for GitHub auth based on mock ID prefix
  const isGithubConnected = user?.id?.startsWith('gh_') || false;

  const templateName = TEMPLATES.find(t => t.id === portfolioData.templateId)?.name || 'Custom';

  const handleSyncClick = () => {
    setIsGithubModalOpen(true);
  };

  const handleGithubSync = async (data: { name: string; description: string; visibility: 'public' | 'private' }) => {
    setSyncing(true);
    // Simulate API call and Auth check
    await new Promise(resolve => setTimeout(resolve, 2000));
    
    setSyncing(false);
    setIsGithubModalOpen(false);
    setShowToast('sync');
    setTimeout(() => setShowToast(null), 3000);
  };

  const handleDeploy = () => {
    setDeploying(true);
    setTimeout(() => {
      setDeploying(false);
      setLiveUrl(`https://${portfolioData.name.toLowerCase().replace(/\s/g, '-') || 'user'}.netlify.app`);
      setShowToast('deploy');
      setTimeout(() => setShowToast(null), 5000);
    }, 2500);
  };

  const handleDownloadZip = async () => {
    try {
      setIsDownloading(true);
      const zip = new JSZip();
      
      // 1. Capture HTML from the preview container
      const previewContainer = document.getElementById('preview-container');
      if (!previewContainer) throw new Error("Preview container not found");
      
      let htmlContent = previewContainer.innerHTML;

      // Clean up the HTML for standalone export
      // Remove sticky preview hacks to ensure full window scrolling works in the exported file
      htmlContent = htmlContent.replace(/sticky top-0 mb-\[-80px\]/g, 'fixed top-0 left-0 right-0');
      
      // Create the full HTML document
      const fullHtml = `
<!DOCTYPE html>
<html lang="en" class="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${portfolioData.name || 'Portfolio'} | Portfoli AI</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600&family=Syne:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
    <style>
      :root { --bg-depth: #050505; --accent: #ccff00; }
      body { background-color: var(--bg-depth); color: white; font-family: 'Inter', sans-serif; overflow-x: hidden; }
      .font-display { font-family: 'Syne', sans-serif; }
      .font-mono { font-family: 'JetBrains Mono', monospace; }
      ::-webkit-scrollbar { width: 8px; }
      ::-webkit-scrollbar-track { background: #0a0a0a; }
      ::-webkit-scrollbar-thumb { background: #333; border-radius: 4px; }
      .glass-panel { background: rgba(20, 20, 20, 0.6); backdrop-filter: blur(20px); border: 1px solid rgba(255, 255, 255, 0.1); }
    </style>
</head>
<body>
    ${htmlContent}
    <script>
      // Restoring scroll interaction logic for the Navbar
      window.addEventListener('scroll', () => {
        const nav = document.querySelector('nav');
        if(!nav) return;
        const navContent = nav.querySelector('div');
        if (window.scrollY > 50) {
          nav.classList.remove('py-8');
          nav.classList.add('py-4');
          if(navContent) {
            navContent.classList.add('bg-black/60', 'backdrop-blur-xl', 'border', 'border-white/10', 'rounded-full', 'py-3', 'px-6');
          }
        } else {
          nav.classList.add('py-8');
          nav.classList.remove('py-4');
          if(navContent) {
            navContent.classList.remove('bg-black/60', 'backdrop-blur-xl', 'border', 'border-white/10', 'rounded-full', 'py-3', 'px-6');
          }
        }
      });
    </script>
</body>
</html>`;

      // 2. Add files to Zip
      zip.file("index.html", fullHtml);
      zip.file("portfolio-data.json", JSON.stringify(portfolioData, null, 2));
      zip.file("README.md", `# ${portfolioData.name} Portfolio\n\nGenerated by Portfoli AI.\n\n## How to Use\n1. Open \`index.html\` in any web browser to view your site.\n2. Upload these files to GitHub Pages, Netlify, or Vercel to host them for free.\n\n## Data\nThe \`portfolio-data.json\` file contains your raw profile data and can be used to restore your session in the Portfoli AI builder.`);

      // 3. Generate and Download
      const content = await zip.generateAsync({type: "blob"});
      const url = window.URL.createObjectURL(content);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${portfolioData.name.toLowerCase().replace(/\s/g, '-') || 'portfolio'}-deploy.zip`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);

      setShowToast('download');
      setTimeout(() => setShowToast(null), 3000);
    } catch (err) {
      console.error("Failed to generate zip", err);
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <>
      <GithubSyncModal 
        isOpen={isGithubModalOpen} 
        onClose={() => setIsGithubModalOpen(false)}
        onSync={handleGithubSync}
        isSyncing={syncing}
        isGithubConnected={isGithubConnected}
        isAuthLoading={isAuthLoading}
        onConnectGithub={loginWithGitHub}
      />
      
      {/* Top Action Bar (Non-sticky here, acts as toolbar for the preview frame) */}
      <div className="bg-slate-900 border-b border-slate-800 py-3 px-6 flex items-center justify-between z-40">
        <div className="flex items-center gap-3">
          <span className="hidden sm:inline text-xs font-bold text-slate-500 uppercase tracking-widest">Environment</span>
          <div className="flex items-center gap-1.5 px-2 py-1 bg-green-500/10 border border-green-500/20 rounded text-green-400 text-[10px] font-bold">
            <div className="w-1.5 h-1.5 bg-green-500 rounded-full animate-pulse" />
            READY ({templateName})
          </div>
        </div>

        <div className="flex items-center gap-3">
          <button 
            onClick={handleSyncClick}
            disabled={syncing}
            className="flex items-center gap-2 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg text-xs font-medium transition-all disabled:opacity-50"
          >
            {syncing ? <Loader2 className="w-3 h-3 animate-spin" /> : <Github className="w-3 h-3" />}
            Sync
          </button>
          <button 
            onClick={handleDownloadZip}
            disabled={isDownloading}
            className="flex items-center gap-2 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg text-xs font-medium transition-all disabled:opacity-50"
          >
            {isDownloading ? <Loader2 className="w-3 h-3 animate-spin" /> : <Download className="w-3 h-3" />}
            Source (.zip)
          </button>
          <button 
            onClick={handleDeploy}
            disabled={deploying}
            className="flex items-center gap-2 px-4 py-1.5 bg-blue-600 hover:bg-blue-500 text-white rounded-lg text-xs font-bold transition-all disabled:opacity-50"
          >
            {deploying ? <Loader2 className="w-3 h-3 animate-spin" /> : <Cloud className="w-3 h-3" />}
            Deploy to Netlify
          </button>
        </div>

        {showToast && (
          <div className="fixed bottom-6 right-6 bg-slate-800 border border-slate-700 p-4 rounded-xl shadow-2xl flex items-center gap-3 animate-in slide-in-from-right-10 z-[120]">
            <CheckCircle className="w-6 h-6 text-green-500" />
            <div>
              <p className="font-bold text-slate-50">
                {showToast === 'sync' ? 'GitHub Repos Synced' : showToast === 'deploy' ? 'Site Deployed Successfully' : 'Download Started'}
              </p>
              <p className="text-xs text-slate-400">
                {showToast === 'sync' ? 'Your latest projects have been pulled.' : showToast === 'deploy' ? 'Your portfolio is live globally.' : 'Source code package prepared.'}
              </p>
              {showToast === 'deploy' && liveUrl && (
                <a href={liveUrl} target="_blank" className="text-blue-400 text-[10px] hover:underline flex items-center gap-1 mt-1">
                  <LinkIcon className="w-2.5 h-2.5" /> {liveUrl}
                </a>
              )}
            </div>
          </div>
        )}
      </div>
    </>
  );
};

const PreviewPage: React.FC = () => {
  const { portfolioData } = usePortfolio();

  return (
    <div className="h-screen bg-slate-950 flex flex-col pt-24 overflow-hidden">
      <ActionHeader />
      <div id="preview-container" className="flex-1 overflow-y-auto bg-black relative scroll-smooth shadow-[inset_0_0_20px_rgba(0,0,0,0.5)]">
        {/* Pass the template bestFor as category to control styling, and isPreview to manage internal layout */}
        <PortfolioView 
          data={portfolioData} 
          category={TEMPLATES.find(t => t.id === portfolioData.templateId)?.bestFor || 'Developer'} 
          isPreview={true}
        />
      </div>
    </div>
  );
};

export default PreviewPage;
